debug: false
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000
    password: none
    jedis:
      pool:
        max-active: 300
        min-idle: 8
        max-idle: 32
        max-wait: -1